-- Default Investor Quest — Financials & Management pillar quest cards (Quest Content Manager)

-- =============================================================================
-- FINANCIALS PILLAR
-- =============================================================================

insert into public.quest_content_cards (
  slug,
  pillar_id,
  quest_type,
  title,
  objective,
  description,
  investor_question,
  why_this_matters,
  plain_english_answer,
  source_filing_type,
  source_section_key,
  source_section_label,
  ai_prompt_template,
  xp_reward,
  quiz_format,
  quiz_config,
  display_order,
  partner_ids,
  is_active,
  updated_at
) values
  (
    'growth',
    'financials',
    'growth',
    'Growth',
    'Assess whether the business is growing.',
    'Mini quest prompts: What is the 3 year revenue growth? What is the breakdown of revenue for their products? What is the breakdown of geographical revenue?',
    'Is the business growing?',
    'Revenue growth shows whether demand for the company''s products or services is expanding.',
    null,
    '10-K',
    'item_7',
    'Item 7 — MD&A',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, answer: Is the business growing? Cover: (1) roughly how revenue has changed over about three years, (2) which products or services drive revenue, and (3) how revenue splits by geography if disclosed. Use 10-K Item 7 — MD&A and Item 8 — Financial Statements only. No jargon—short paragraphs or bullets.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    10,
    '{}',
    true,
    now()
  ),
  (
    'profitability',
    'financials',
    'profitability',
    'Profitability',
    'Assess whether the company is profitable.',
    'Mini quest prompts: Are profit margins improving or shrinking? Is earnings per share growing?',
    'Is the company profitable?',
    'EPS growth reflects how much profit belongs to each shareholder.',
    null,
    '10-K',
    'item_7',
    'Item 7 — MD&A',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, answer: Is the company profitable? Explain whether profit margins are improving or shrinking and whether earnings per share (EPS) is growing. Use 10-K Item 7 — MD&A and Item 8 — Financial Statements only. Define terms simply when you use them.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    20,
    '{}',
    true,
    now()
  ),
  (
    'expenses',
    'financials',
    'expenses',
    'Expenses',
    'See how efficiently the company operates.',
    'Mini quest prompts: How are operating expenses changing? Is the company spending to grow the business?',
    'How efficiently is the company operating?',
    'Rising expenses without revenue growth may signal inefficiency.',
    null,
    '10-K',
    'item_7',
    'Item 7 — MD&A',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, answer: How efficiently is the company operating? Describe how operating expenses are changing and whether spending looks focused on growth or waste. Use only 10-K Item 7 — MD&A. Keep it practical for a beginner.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    30,
    '{}',
    true,
    now()
  ),
  (
    'cash',
    'financials',
    'cash',
    'Cash',
    'Check whether the business generates real cash.',
    'Mini quest prompts: Is operating cash flow increasing? How is cash being used?',
    'Is the business generating real cash?',
    'Strong operating cash flow shows the business generates real cash from operations.',
    null,
    '10-K',
    'item_7',
    'Item 7 — MD&A',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, answer: Is the business generating real cash? Explain whether operating cash flow is increasing and how the company uses cash (operations, investments, debt paydown, dividends, buybacks). Use 10-K Item 7 — MD&A and Item 8 — Financial Statements only.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    40,
    '{}',
    true,
    now()
  ),
  (
    'financial-strength',
    'financials',
    'financial-strength',
    'Financial Strength',
    'Gauge balance-sheet strength and obligations.',
    'Mini quest prompts: Does the company have more cash or debt? What financial obligations does the company have?',
    'How strong is the company financially?',
    'Companies with strong balance sheets can survive downturns and invest in growth.',
    null,
    '10-K',
    'item_8',
    'Item 8 — Financial Statements',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, answer: How strong is the company financially? Address whether it has more cash or debt (in simple terms) and what major financial obligations investors should know. Use 10-K Item 8 — Financial Statements and supporting notes from Item 7 — MD&A if needed. Avoid accounting jargon.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    50,
    '{}',
    true,
    now()
  )
on conflict (pillar_id, slug) do update set
  quest_type = excluded.quest_type,
  title = excluded.title,
  objective = excluded.objective,
  description = excluded.description,
  investor_question = excluded.investor_question,
  why_this_matters = excluded.why_this_matters,
  plain_english_answer = excluded.plain_english_answer,
  source_filing_type = excluded.source_filing_type,
  source_section_key = excluded.source_section_key,
  source_section_label = excluded.source_section_label,
  ai_prompt_template = excluded.ai_prompt_template,
  xp_reward = excluded.xp_reward,
  quiz_format = excluded.quiz_format,
  quiz_config = excluded.quiz_config,
  display_order = excluded.display_order,
  partner_ids = excluded.partner_ids,
  is_active = excluded.is_active,
  updated_at = now();

-- =============================================================================
-- MANAGEMENT PILLAR
-- =============================================================================

insert into public.quest_content_cards (
  slug,
  pillar_id,
  quest_type,
  title,
  objective,
  description,
  investor_question,
  why_this_matters,
  plain_english_answer,
  source_filing_type,
  source_section_key,
  source_section_label,
  ai_prompt_template,
  xp_reward,
  quiz_format,
  quiz_config,
  display_order,
  partner_ids,
  is_active,
  updated_at
) values
  (
    'board-leadership',
    'management',
    'board-leadership',
    'Board & Leadership',
    'Meet the leaders and assess whether you would trust them.',
    'Mini quest prompts: Who are the key executives and what experience do they have? How long have executives been with the company? What has management achieved so far?',
    'Meet the people in charge and see if you''d trust them with your money.',
    'Experienced leaders = fewer mistakes.',
    null,
    'DEF 14A',
    'proxy_executives',
    'Executive Officers',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, introduce the people in charge: key executives, their relevant experience, how long they have been with the company, and notable achievements. Use DEF 14A sections on executive officers and board leadership. Write as if explaining to a friend—no jargon.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    10,
    '{}',
    true,
    now()
  ),
  (
    'executive-compensation',
    'management',
    'executive-compensation',
    'Executive Compensation',
    'Understand how executives are paid and whether pay aligns with shareholders.',
    'Mini quest prompts: Do executives own company stock? How does executive pay compare to performance? How is executive pay structured? What performance targets determine bonuses?',
    'See how they get paid — and if they win when you win.',
    'Good pay rewards long-term success, not quick wins.',
    null,
    'DEF 14A',
    'proxy_compensation',
    'Executive Compensation',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, explain how executives get paid: stock ownership, pay vs performance, pay structure (salary, bonus, equity), and what targets drive bonuses. Use only DEF 14A executive compensation disclosures. Keep it fair and easy to understand.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    20,
    '{}',
    true,
    now()
  ),
  (
    'capital-allocation',
    'management',
    'capital-allocation',
    'Capital Allocation',
    'See how management uses cash and profits.',
    'Mini quest prompts: How does the company use its profits? Is management returning cash to shareholders?',
    'See how the company uses money — smart moves or costly mistakes.',
    'Smart spending grows your investment.',
    null,
    'DEF 14A',
    'proxy_governance',
    'Corporate Governance',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, explain how the company uses money: reinvestment, acquisitions, dividends, buybacks, or debt reduction—and whether management is returning cash to shareholders. Use DEF 14A governance and compensation context plus 10-K Item 7 — MD&A where relevant. Focus on what a beginner needs to know.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    30,
    '{}',
    true,
    now()
  ),
  (
    'governance-control',
    'management',
    'governance-control',
    'Governance & Control',
    'Check oversight, independence, and investor protections.',
    'Mini quest prompts: Who sits on the board and are they independent? What committees oversee management decisions? Are there related-party transactions or conflicts of interest? What happens if executives leave or the company is acquired?',
    'Check if anyone is keeping management in check and protecting investors.',
    'Independent boards help prevent management from acting against shareholders.',
    null,
    'DEF 14A',
    'proxy_governance',
    'Corporate Governance',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, explain governance and control: board members and independence, key committees, related-party deals or conflicts, and what happens if leaders leave or the company is sold. Use only DEF 14A corporate governance sections. Be clear and neutral.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    40,
    '{}',
    true,
    now()
  )
on conflict (pillar_id, slug) do update set
  quest_type = excluded.quest_type,
  title = excluded.title,
  objective = excluded.objective,
  description = excluded.description,
  investor_question = excluded.investor_question,
  why_this_matters = excluded.why_this_matters,
  plain_english_answer = excluded.plain_english_answer,
  source_filing_type = excluded.source_filing_type,
  source_section_key = excluded.source_section_key,
  source_section_label = excluded.source_section_label,
  ai_prompt_template = excluded.ai_prompt_template,
  xp_reward = excluded.xp_reward,
  quiz_format = excluded.quiz_format,
  quiz_config = excluded.quiz_config,
  display_order = excluded.display_order,
  partner_ids = excluded.partner_ids,
  is_active = excluded.is_active,
  updated_at = now();
