-- Forces hub map — four category overlay cards (display_order 1–4)

insert into public.quest_content_cards (
  slug,
  pillar_id,
  quest_type,
  title,
  objective,
  description,
  investor_question,
  why_this_matters,
  plain_english_answer,
  source_filing_type,
  source_section_key,
  source_section_label,
  ai_prompt_template,
  xp_reward,
  quiz_format,
  quiz_config,
  display_order,
  forces_category,
  hub_icon,
  hub_subtitle,
  hub_card_count,
  hub_route,
  hub_locked,
  partner_ids,
  is_active,
  updated_at
) values
  (
    'forces-hub-positive-inside',
    'forces',
    'risk',
    'Positive Inside Forces',
    'Strengths within the company''s control',
    'Explore internal tailwinds that can lift margins, execution, and investor confidence.',
    'What internal strengths could help this company win?',
    'Internal strengths are forces the company can actually control — they shape how resilient the business is when markets turn.',
    'Strengths within the company''s control',
    '10-K',
    'item_1a',
    'Item 1A — Risk Factors',
    'Guide the investor through Positive Inside Forces for {Company.name}.',
    0,
    'multiple-choice',
    null,
    1,
    'positive-inside',
    'positive-inside',
    'What internal strengths could help this company win?',
    4,
    '/forces/category/positive-inside',
    false,
    '{}',
    true,
    now()
  ),
  (
    'forces-hub-positive-outside',
    'forces',
    'industry',
    'Positive Outside Forces',
    'Tailwinds outside the company''s control',
    'Explore external tailwinds — demand, regulation, and macro — that can lift the stock without perfect execution.',
    'What external tailwinds could lift this company?',
    'Outside forces can expand the opportunity set even when management is merely competent — investors separate luck from skill.',
    'Tailwinds outside the company''s control',
    '10-K',
    'item_1a',
    'Item 1A — Risk Factors',
    'Guide the investor through Positive Outside Forces for {Company.name}.',
    0,
    'multiple-choice',
    null,
    2,
    'positive-outside',
    'positive-outside',
    'What external tailwinds could lift this company?',
    5,
    '/forces/category/positive-outside',
    true,
    '{}',
    true,
    now()
  ),
  (
    'forces-hub-negative-inside',
    'forces',
    'risk',
    'Negative Inside Forces',
    'Risks within the company''s control',
    'Explore internal risks — operations, balance sheet, and reputation — that management must contain.',
    'What internal risks could break the investment case?',
    'Internal risks are where management accountability is clearest — execution slips and balance-sheet stress show up here first.',
    'Risks within the company''s control',
    '10-K',
    'item_1a',
    'Item 1A — Risk Factors',
    'Guide the investor through Negative Inside Forces for {Company.name}.',
    0,
    'multiple-choice',
    null,
    3,
    'negative-inside',
    'negative-inside',
    'What internal risks could break the investment case?',
    5,
    '/forces/category/negative-inside',
    true,
    '{}',
    true,
    now()
  ),
  (
    'forces-hub-negative-outside',
    'forces',
    'industry',
    'Negative Outside Forces',
    'Headwinds outside the company''s control',
    'Explore external headwinds — competition, macro, regulation, and geopolitics — that can pressure results.',
    'What external headwinds could pressure this company?',
    'Macro and industry shocks can overwhelm good operators — mapping outside forces helps you size downside scenarios.',
    'Headwinds outside the company''s control',
    '10-K',
    'item_1a',
    'Item 1A — Risk Factors',
    'Guide the investor through Negative Outside Forces for {Company.name}.',
    0,
    'multiple-choice',
    null,
    4,
    'negative-outside',
    'negative-outside',
    'What external headwinds could pressure this company?',
    5,
    '/forces/category/negative-outside',
    true,
    '{}',
    true,
    now()
  )
on conflict (pillar_id, slug) do update set
  title = excluded.title,
  objective = excluded.objective,
  description = excluded.description,
  investor_question = excluded.investor_question,
  why_this_matters = excluded.why_this_matters,
  plain_english_answer = excluded.plain_english_answer,
  display_order = excluded.display_order,
  forces_category = excluded.forces_category,
  hub_icon = excluded.hub_icon,
  hub_subtitle = excluded.hub_subtitle,
  hub_card_count = excluded.hub_card_count,
  hub_route = excluded.hub_route,
  hub_locked = excluded.hub_locked,
  is_active = excluded.is_active,
  updated_at = now();
