-- Default Investor Quest — Business pillar quest cards (Quest Content Manager)

insert into public.quest_content_cards (
  slug,
  pillar_id,
  quest_type,
  title,
  objective,
  description,
  investor_question,
  why_this_matters,
  plain_english_answer,
  source_filing_type,
  source_section_key,
  source_section_label,
  ai_prompt_template,
  xp_reward,
  quiz_format,
  quiz_config,
  display_order,
  partner_ids,
  is_active,
  updated_at
) values
  (
    'snapshot',
    'business',
    'snapshot',
    'Quick Snapshot',
    'Get a quick overview of what the company does.',
    'A beginner-friendly snapshot of the business model using the 10-K Business section.',
    'What does this company actually do?',
    'Before judging the stock, investors need to understand the business in simple terms.',
    null,
    '10-K',
    'item_1',
    'Item 1 — Business',
    'You are helping a beginner investor learn about {Company.name} ({Company.ticker}). In plain English (no jargon), explain what this company actually does: what it sells, who its customers are, and one sentence on why the business matters. Use only the 10-K Item 1 — Business section. Keep it to 3–5 short sentences.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    10,
    '{}',
    true,
    now()
  ),
  (
    'revenue',
    'business',
    'revenue',
    'Revenue',
    'See where the company earns its money.',
    'Trace revenue drivers from the 10-K Business section in plain language.',
    'Where does the company actually make its money?',
    'A company''s revenue shows what really drives the business.',
    null,
    '10-K',
    'item_1',
    'Item 1 — Business',
    'You are helping a beginner investor understand {Company.name} ({Company.ticker}). In simple terms, explain where the company makes its money: main products or services, key regions or markets, and who pays them. Use only the 10-K Item 1 — Business section. Use short paragraphs or bullet points.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    20,
    '{}',
    true,
    now()
  ),
  (
    'operations',
    'business',
    'operations',
    'Operations',
    'See how the business runs day to day.',
    'How products reach customers and how the company executes, from Item 1 — Business.',
    'How does the business actually run day-to-day?',
    'Strong operations help a company deliver, grow, and compete.',
    null,
    '10-K',
    'item_1',
    'Item 1 — Business',
    'You are helping a beginner investor understand {Company.name} ({Company.ticker}). In plain English, describe how the business runs day-to-day: how products or services reach customers and what kind of workforce or partners make it happen. Use only the 10-K Item 1 — Business section. Keep it practical and easy to read.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    30,
    '{}',
    true,
    now()
  ),
  (
    'advantage',
    'business',
    'advantage',
    'Advantage',
    'Find what gives the company an edge.',
    'Competitive strengths and protections from the 10-K Business section.',
    'What gives this company an edge?',
    'Competitive advantages can help protect profits over time.',
    null,
    '10-K',
    'item_1',
    'Item 1 — Business',
    'You are helping a beginner investor evaluate {Company.name} ({Company.ticker}). In plain English, explain what gives this company an edge over rivals (for example: brand, technology, scale, patents, ecosystem, or customer loyalty). Use only the 10-K Item 1 — Business section. Be specific but avoid jargon.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    40,
    '{}',
    true,
    now()
  ),
  (
    'industry',
    'business',
    'industry',
    'Industry',
    'Understand the industry context and competition.',
    'Industry landscape, rivals, and competitive intensity from Item 1 — Business.',
    'How tough is the industry?',
    'Even a good company can struggle in a difficult or highly competitive industry.',
    null,
    '10-K',
    'item_1',
    'Item 1 — Business',
    'You are helping a beginner investor place {Company.name} ({Company.ticker}) in context. In plain English, describe how tough the industry is: main competitors, how competitive the market feels, and any rules or regulations that matter. Use only the 10-K Item 1 — Business section. Keep it clear for someone new to investing.',
    50,
    'multiple-choice',
    '{"passThreshold": 0.66}'::jsonb,
    50,
    '{}',
    true,
    now()
  )
on conflict (pillar_id, slug) do update set
  quest_type = excluded.quest_type,
  title = excluded.title,
  objective = excluded.objective,
  description = excluded.description,
  investor_question = excluded.investor_question,
  why_this_matters = excluded.why_this_matters,
  plain_english_answer = excluded.plain_english_answer,
  source_filing_type = excluded.source_filing_type,
  source_section_key = excluded.source_section_key,
  source_section_label = excluded.source_section_label,
  ai_prompt_template = excluded.ai_prompt_template,
  xp_reward = excluded.xp_reward,
  quiz_format = excluded.quiz_format,
  quiz_config = excluded.quiz_config,
  display_order = excluded.display_order,
  partner_ids = excluded.partner_ids,
  is_active = excluded.is_active,
  updated_at = now();
